language: python
sudo: false # if false, use TravisCI's container based build

matrix:
    include:
    - python: 3.6
      env: CONDA_ENV=py36

addons:
    apt:
        packages:
            - ccache

cache:
    directories:
        - $HOME/.ccache

# setup miniconda for numpy, scipy, pandas
before_install:
    - echo "before install"
    - export PATH=/usr/lib/ccache:$PATH
    - wget https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    
install:
    - echo "install"
    - conda env create --file ci/requirements-$CONDA_ENV.yml
    - source activate test_env # all envs are named test_env in the yml files
    - conda list
    - echo $PATH
    - ls -l /home/travis/miniconda/envs/test_env/lib
    # CDL use the github master
    # - pip install pyomo
    - pip install git+https://github.com/PyUtilib/pyutilib.git
    - pip install git+https://github.com/Pyomo/pyomo.git
    - pip install git+https://github.com/coramin/coramin.git
    - conda install -c conda-forge ipopt
    - conda install -c conda-forge coincbc
    - python setup.py develop

script:
    # CDL: This command is somehow recursing into Pyomo doctests - let's add doctest manually in the correct folder when
    # we have them
    # - nosetests -v --nologcapture --with-coverage --with-doctest --doctest-extension=.rst --cover-package=egret egret
    - nosetests -v --nologcapture --with-coverage --cover-package=egret egret

after_success:
    coveralls
